### ISSUE TITLE
Bussin does not work on a fresh install of NPM.

### ISSUE THREAD

**Issue by CuriousCodingCanadian** [face-hh/bussin#22]
Bussin, and Bussin X, do not work on a fresh install of NPM on debian.

```> bussin
> npx ts-node src/main.ts

/home/eesa/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/main.ts:5:27 - error TS2307: Cannot find module 'readline/promises' or its corresponding type declarations.

5 import * as readline from 'readline/promises';
                            ~~~~~~~~~~~~~~~~~~~
src/main.ts:6:30 - error TS2307: Cannot find module 'fs' or its corresponding type declarations.

6 import { readFileSync } from "fs";
                               ~~~~
src/main.ts:10:12 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

10     input: process.stdin,
              ~~~~~~~
src/main.ts:11:13 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

11     output: process.stdout
               ~~~~~~~
src/main.ts:14:14 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

14 const file = process.argv[2];
                ~~~~~~~
src/main.ts:28:18 - error TS2550: Property 'endsWith' does not exist on type 'string'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2015' or later.

28     if (filename.endsWith('.bsx')) input = await transcribe(input);
                    ~~~~~~~~
src/main.ts:36:16 - error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.

36 async function repl() {
                  ~~~~
src/main.ts:47:13 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

47             process.exit(1);
               ~~~~~~~

    at createTSError (/home/eesa/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/home/eesa/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/home/eesa/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/home/eesa/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/home/eesa/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.require.extensions.<computed> [as .ts] (/home/eesa/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12) {
  diagnosticCodes: [
    2307, 2307, 2580,
    2580, 2580, 2550,
    2705, 2580
  ]
}
```

**Comment by 0x408** [comment]
Are you sure that you have Node.js type definitions installed? 
Try running the following:

`npm i --save-dev @types/node`

**Comment by hcwf** [comment]
Did you try to run `npm install` with the URL supplied? I had to `git clone` the repository then cd into it and run `npm install` from there to get it to work.

**Comment by Symmettry** [comment]
Not a bug, just do what's mentioned above.
